### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Airkek** [kagurazakasanae/Il2CppDumper-YuanShen#10]
Can you help me with dumping global-metadata.dat?
I will pay if u need

**Comment by kagurazakasanae** [comment]
nope
but i have a dump of older version(1.0.0) and i can send that to you if you want.

**Comment by Airkek** [comment]
I need global_metadata and UserAssembly.dll (original) of any version, It would be fine :D

**Comment by kagurazakasanae** [comment]
if that's all u need just check https://github.com/kagurazakasanae/MelonLoader-YuanShen/releases/tag/1.0
decompress downloaded file and check the folder "MelonLoader\Managed", this contains all files that this dumper will created(which called dummy dlls)
