### ISSUE TITLE
globalmetadata读写研究

### ISSUE THREAD

**Issue by ghost** [kagurazakasanae/Il2CppDumper-YuanShen#11]
感谢宝藏话题
pc版的gameassembly.dll 里面有个closeZStream，createZStream头，中间夹着所有il2cpp，再以readZStream，writeZStream结尾，这些stream流是一种普遍的加密方法吗= =？  或者有人知道哪里有相关学习资料吗
我试着抓包和砸壳20200818的0.9版本（看看是不是可以找到他们的一些疏忽），然而得到的脱壳ipa使用IL2cppdumper依然无法使用，这种读写globalmetadata的方法以前从没见过，orz
★：偷偷查阅关闭的话题已发现惊喜╰(*°▽°*)╯就是想讨论下这个读写方法叫啥名字，偷学一下- -、

**Comment by ghost** [comment]
![newscreen42288000](https://user-images.githubusercontent.com/75260887/102002428-53998e00-3d37-11eb-860a-9acf58b71ece.jpg)
![newscreen42334203](https://user-images.githubusercontent.com/75260887/102002430-54cabb00-3d37-11eb-9362-cdee6c9cd732.jpg)

**Comment by kagurazakasanae** [comment]
参考该文章
[https://www.twblogs.net/a/5d11f8ecbd9eee1e5c821fba](https://www.twblogs.net/a/5d11f8ecbd9eee1e5c821fba)
虽然目前版本加密方式已有变动，但大体思路不变
且由于metadata的文件格式有变化，解密之后用原版dumper也是无法导出的
