### ISSUE TITLE
弱弱的问问， 1.2 版本命令行错误

### ISSUE THREAD

**Issue by vmtest888** [kagurazakasanae/Il2CppDumper-YuanShen#12]
弱弱的问问， 1.2 版本命令行错误

`
Initializing metadata...
System.OverflowException: 算术运算导致溢出。
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) 位置 C:\Users\Administrator\Downloads\Il2CppDumper-YuanShen-master\Il2CppDumper\IO\BinaryStream.cs:行号 198
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](UInt64 addr, Int64 count) 位置 C:\Users\Administrator\Downloads\Il2CppDumper-YuanShen-master\Il2CppDumper\IO\BinaryStream.cs:行号 209
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\Users\Administrator\Downloads\Il2CppDumper-YuanShen-master\Il2CppDumper\Il2Cpp\Metadata.cs:行号 87
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\Users\Administrator\Downloads\Il2CppDumper-YuanShen-master\Il2CppDumper\Program.cs:行号 122
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\Users\Administrator\Downloads\Il2CppDumper-YuanShen-master\Il2CppDumper\Program.cs:行号 97
Press any key to exit...

`

**Comment by kagurazakasanae** [comment]
该项目仅在1.0上进行过测试，offset等可能已经变化所以不适用

**Comment by 344389541** [comment]
大佬，请教一下，我看到你另外一个工程是游戏和驱动通信的部分。&nbsp;&nbsp;&nbsp;这个是你dump的1.0的，然后逆向其中的某个dll么？
------&nbsp;原始邮件&nbsp;------
发件人:&quot;神楽坂早苗&quot;<notifications@github.com&gt;;
发送时间:2021年1月6日(星期三)&nbsp;晚上8:55
收件人:&quot;kagurazakasanae/Il2CppDumper-YuanShen&quot;<Il2CppDumper-YuanShen@noreply.github.com&gt;;
抄送人:&quot;344389541&quot;<344389541@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:Re:&nbsp;[kagurazakasanae/Il2CppDumper-YuanShen]&nbsp;弱弱的问问，&nbsp;1.2&nbsp;版本命令行错误&nbsp;(#12)



 
该项目仅在1.0上进行过测试，offset等可能已经变化所以不适用
 
&mdash;

**Comment by kagurazakasanae** [comment]
该项目为逆向UserAssembly.dll中对应的il2cpp加载函数并更新il2cppdumper中的offset来做到dump原神UserAssembly.dll结构，仅适用于1.0版本，后续版本没有更多研究。

**Comment by 344389541** [comment]
我是在研究游戏怎么脱离驱动运行。&nbsp;也是刚接触unity逆向，github上看到你的c#，抄袭了一下，在应用层hook&nbsp;createfile，deviceiocontrol进行协议伪造，只实现少数几个消息，但是登录的时候服务器返回错误。。所以也是一头雾水。大佬手上还有驱动相关的这个dll文件吗，我想研究一下。
------&nbsp;原始邮件&nbsp;------
发件人:&quot;神楽坂早苗&quot;<notifications@github.com&gt;;
发送时间:2021年1月7日(星期四)&nbsp;凌晨0:42
收件人:&quot;kagurazakasanae/Il2CppDumper-YuanShen&quot;<Il2CppDumper-YuanShen@noreply.github.com&gt;;
抄送人:&quot;344389541&quot;<344389541@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:Re:&nbsp;[kagurazakasanae/Il2CppDumper-YuanShen]&nbsp;弱弱的问问，&nbsp;1.2&nbsp;版本命令行错误&nbsp;(#12)



 
该项目为逆向UserAssembly.dll中对应的il2cpp加载函数并更新il2cppdumper中的offset来做到dump原神UserAssembly.dll结构，仅适用于1.0版本，后续版本没有更多研究。
 
&mdash;

**Comment by kagurazakasanae** [comment]
想要脱离驱动你需要实现我c#控制驱动项目中的所有操作码，同时需要过掉程序对自己的crc校验
