### ISSUE TITLE
如何修改il2cppdumper

### ISSUE THREAD

**Issue by DDWSdwqdq** [kagurazakasanae/Il2CppDumper-YuanShen#3]
大佬能加个q吗，如何修改il2cppdumper去支持原神解析gm文件

**Comment by kagurazakasanae** [comment]
现在这个就是可以解析当前版本原神metadata文件的，但是原神metadata是加密的，你需要先从内存中导出解密之后的文件再解析，如果你需要解析过的输出，请参考这个release中的内容https://github.com/kagurazakasanae/MelonLoader-YuanShen/releases/tag/1.0
