### ISSUE TITLE
Il2CppDumper-yuanshen

### ISSUE THREAD

**Issue by zhengmiemie** [kagurazakasanae/Il2CppDumper-YuanShen#7]
stringDecryptionBlob = File.ReadAllBytes("D:\\genshinimpactre\\decryption_blob.bin");
decryption_blob.bin 怎么获取？

**Comment by kagurazakasanae** [comment]
ida打开UserAssembly.dll找到加载global-metadata.dat的函数，从函数的返回内存地址上dump

**Comment by zhengmiemie** [comment]
解密完global-metadata.dat之后 dump出 解密后的数据，之前dump的大小跟global-metadata.dat大小一样。但是，师傅给的例子好像只有20K 这个大小是有关系嘛。好像懂了，又好像没懂。呜呜呜




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "神楽坂早苗"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 中午12:01
收件人: "kagurazakasanae/Il2CppDumper-YuanShen"<Il2CppDumper-YuanShen@noreply.github.com&gt;; 
抄送: "(13L12T13) 活动中心"<1224410990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kagurazakasanae/Il2CppDumper-YuanShen] Il2CppDumper-yuanshen (#7)





 
ida打开UserAssembly.dll找到加载global-metadata.dat的函数，从函数的返回内存地址上dump

**Comment by kagurazakasanae** [comment]
正常dump的大小应当跟解密前的global-metadata.dat大小一致，如果不同则说明有误

**Comment by zhengmiemie** [comment]
懂啦，师傅牛批！

**Comment by zhengmiemie** [comment]
System.ArgumentOutOfRangeException: 流长度必须为非负值，并小于“2^31 - 1 - 原始值”的计算结果。
参数名: value
&nbsp; &nbsp;在 System.IO.MemoryStream.set_Position(Int64 value)

师傅遇到这样的问题，是因为global-metadata.dat太大了么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "神楽坂早苗"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 中午12:07
收件人: "kagurazakasanae/Il2CppDumper-YuanShen"<Il2CppDumper-YuanShen@noreply.github.com&gt;; 
抄送: "(13L12T13) 活动中心"<1224410990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kagurazakasanae/Il2CppDumper-YuanShen] Il2CppDumper-yuanshen (#7)





 
正常dump的大小应当跟解密前的global-metadata.dat大小一致，如果不同则说明有误

**Comment by kagurazakasanae** [comment]
该项目的原始commit是针对1.0.0版本原神的，后面的更新都是别人的pull request，我没有验证offset正确性，可能有错误也可能结构有变化

**Comment by zhengmiemie** [comment]
我这里是1.0.0版本的原神数据~ 可能我哪里做错了 我在康康



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "神楽坂早苗"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 中午12:43
收件人: "kagurazakasanae/Il2CppDumper-YuanShen"<Il2CppDumper-YuanShen@noreply.github.com&gt;; 
抄送: "(13L12T13) 活动中心"<1224410990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kagurazakasanae/Il2CppDumper-YuanShen] Il2CppDumper-yuanshen (#7)





 
该项目的原始commit是针对1.0.0版本原神的，后面的更新都是别人的pull request，我没有验证offset正确性，可能有错误也可能结构有变化

**Comment by kagurazakasanae** [comment]
1.0.0的话记得下最原始的commit，现在的版本里面有其他人针对1.0.1的更新

**Comment by zhengmiemie** [comment]
嗯~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "神楽坂早苗"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 中午12:47
收件人: "kagurazakasanae/Il2CppDumper-YuanShen"<Il2CppDumper-YuanShen@noreply.github.com&gt;; 
抄送: "(13L12T13) 活动中心"<1224410990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kagurazakasanae/Il2CppDumper-YuanShen] Il2CppDumper-yuanshen (#7)





 
1.0.0的话记得下最原始的commit，现在的版本里面有其他人针对1.0.1的更新
