### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ardikaa** [kagurazakasanae/Il2CppDumper-YuanShen#8]
Sir can u make tutorial how to use this, i cant understand because there so many file and i cant see exe file

**Comment by kagurazakasanae** [comment]
it's just for research purposes and it's not even tested for current version, so if you need a tutorial this is not something for you.

**Comment by ardikaa** [comment]
> it's just for research purposes and it's not even tested for current version, so if you need a tutorial this is not something for you.

Yes but i need your help for use this sir, im testing dump with il2cpp dumper but in there file i can see exe file and i know how to use but this file i cant see that, so how i can use this file sir? Need your answer

**Comment by kagurazakasanae** [comment]
sorry i've no way to tell u how to use that since it require manually dump data from memory which requires some knowledge of reverse engineering.
but if you just want the output that this dumper created, i can provide u one although it's from older version not current one.

**Comment by ardikaa** [comment]
I want use this for dump Genshin impact sir, so maybe u can help me for this?
I try other dump but its not work, so i see your post and i think maybe its work, u can help me sir?

**Comment by kagurazakasanae** [comment]
if that's all u need just check https://github.com/kagurazakasanae/MelonLoader-YuanShen/releases/tag/1.0
decompress downloaded file and check the folder "MelonLoader\Managed", this contains all files that this dumper will created(which called dummy dlls)
NOTICE: DUMMY DLL WILL CONTAINS ONLY BASIC STRUCTURE OF Genshin Impact's IL2CPP FUNCTIONS, NO SOURCE CODE INCLUDED.

**Comment by ardikaa** [comment]
I will try now, thanks sir

**Comment by ardikaa** [comment]
Wait sir, this file can use for genshin impact android version? Because i try to dump android version not pc😅

**Comment by kagurazakasanae** [comment]
nope, this is for PC and this project is also designed for PC version.

**Comment by ardikaa** [comment]
So no have solution for Android version?:(

**Comment by kagurazakasanae** [comment]
the one you've forked https://github.com/Perfare/Riru-Il2CppDumper is actually designed for this purpose, you will have to find a way to use that though.

**Comment by ardikaa** [comment]
Okay sir, thanks for help me
